# Gradle
org.gradle.jvmargs=-Xmx2G -Djava.net.preferIPv4Stack=true
org.gradle.parallel=true
org.gradle.internal.http.connectionTimeout=60000
org.gradle.internal.http.socketTimeout=120000

# Fabric
minecraft_version=1.20.1
yarn_mappings=1.20.1+build.10
loader_version=0.15.11
fabric_version=0.92.2+1.20.1

# MTR
mtr_version=4.0.5

# Mod
mod_version=1.9.34
maven_group=com.mtrpsdlcd
archives_base_name=mtr-psd-lcd
